src/pocketmine/Server.php
Whichever guy did that, somehow this one just got missed out?
=> Use of Utils::getRandomBytes(16)

README.md
Do you guys still have access to the Twitter account? I just noticed that it never got updated. If you still want to use it though, by all means keep this link in here :)
=> Remove Twitter Link

src/pocketmine/Player.php
https://forums.pmmp.io/threads/bug-cmd.247
=> Fix ./command detection by old plugins

src/pocketmine/nbt/NBT.php
Just another simple fix for simple mistake.
=> Fix for getArray() [NBT]

src/pocketmine/command/CommandReader.php
This PR tries to fix #104, through reopening stdin on corruption.
It also closes stdin on shutdown.
~This is untested due to the lack of access to a windows OS for me currently.~
=> Might fix #104 

src/pocketmine/Server.php, src/pocketmine/command/defaults/StatusCommand.php
Fixes #173 and provides a more accurate measure of main thread performance.
=> Report CPU and tick usage accurately using averages

src/pocketmine/Player.php
=> Fixed unused variable being created.

src/pocketmine/tile/Chest.php
I'm unsure if this may cause any other issues, please test carefully.
Closes #256.
=> Fixed double chest tile memory leak on shutdown, close #256

src/pocketmine/MemoryManager.php
If I found this earlier I would of combined it with my last PR. :/
I can't believe this was not closed.
=> Fixed "Too many open files"

src/pocketmine/command/SimpleCommandMap.php
Fixes #423, however I am unsure if this may also be caused by plugins at runtime. Please review.
=> Added detection for recursive server aliases

src/pocketmine/entity/Human.php
Fixed hunger not saving whatsoever. Tested extensively 👍
=> Fixed hunger not saving

src/pocketmine/level/sound/PopSound.php
Fixes PopSound giving failed button click sound.
=> Fix PopSound giving failed click sound.

src/pocketmine/scheduler/AsyncTask.php
Not sure whether this ought to be returning null or throwing an exception.
=> Fixed undefined offset when retrieving something from the thread store that doesn't exist

.github/ISSUE_TEMPLATE.md, src/pocketmine/MemoryManager.php, src/pocketmine/PocketMine.php, src/pocketmine/level/Level.php, src/pocketmine/utils/Binary.php
=> Drop support for 32 bit systems/PHP

src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter.php
Minecraft Windows 10 Edition is stupid and sends empty strings inside form response JSON without quotes, for example `["hello",,"sunshine"]` if the second input field was left empty.
This pull request adds a hack to fix this bug.
None on our issue tracker because this is an unreleased version, but this has been a bug that's plagued third party forms implementations for a while.
Form responses from MCW10 containing empty strings _should_ now decode correctly.
Tested with the following JSON blobs:
```
[\n   \"a\",\"b,c,d,e\\\"   \",,0,1,2, false, 0.001]
0
false
NULL
["\",,\"word","a\",,\"word2",]
```
Please test this and try and break it however you can.
=> Added a hack for MC W10 form JSON empty strings bug

src/pocketmine/Player.php
`Player->addWindow()` permits some undefined behaviour. This PR is intended to eliminate these undefined behaviours and handle such cases properly.
The following changes have been made
- Don't allow the same window ID to be used when it's already in use
- Detect window ID collisions when selecting IDs for regular containers (should never happen, but anything is possible)
- `addWindow()` now _may_ throw `InvalidArgumentException` if attempting to use a `forceId` which is already occupied by another inventory.
- `addWindow()` now _may_ throw `InvalidStateException` if no IDs are free for use when opening a regular window (for example a chest). Since there are nearly 100 possible IDs to use, this is unlikely to ever happen, but it should be checked anyway.
- `addWindow()` will now …
=> Player: Tighten validity checks for addWindow()

src/pocketmine/item/Item.php
=> Item: fix for setCustomName

src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter.php
fixes #3113
additional test factors have been added to the unit testing suite, and all current tests are passing.
=> Fixed decoding form responses with double commas inside quotes

src/pocketmine/plugin/PluginBase.php, src/pocketmine/utils/Utils.php
=> Improved support for paths with backslashes on Unix filesystems

src/pocketmine/Player.php, src/pocketmine/entity/Entity.php
Relevant issues
Fixes #3438 
Tests
Tested in my Ubuntu 18.04
=> Fix walk sounds

src/pocketmine/PocketMine.php, tests/phpstan/configs/l7-baseline.neon
When the server is going to be turned off, it is a good idea to release the server.lock file.
No.
No.
Yes.
Tried to start and stop the server. No errors occurred.
=> Release server.lock file when shutdown the server.

src/item/Bow.php, src/item/ConsumableItem.php, src/item/Releasable.php, src/item/Useable.php, src/player/Player.php
Fixed using items by adding a Releasable interface
In my Ubuntu 18.04
=> Add Releasable interface

src/pocketmine/block/Sugarcane.php
Call BlockGrowEvent when sugarcane grows
=> Call BlockGrowEvent when sugarcane grows

src/world/biome/MountainsBiome.php
Adds emerald ore in mountains biome.
=> Emerald ore in Mountains biome

src/pocketmine/item/Bucket.php, src/pocketmine/item/Item.php, src/pocketmine/tile/Furnace.php
This pull request fixes the disappearance of a lava bucket when used in a furnace.
It was a little strange to add a method for the sake of one item
But maybe someone wants to create custom items and this method will definitely come in handy :)
* Fixes #2385
=> Fixed a bucket of lava disappearing when used in a furnace

BUILDING.md
=> fix prebuilt binaries link in BUILDING.md

src/player/Player.php
This PR aims to fix #4341.
* Fixes #4341 
N/A
N/A
N/A
=> Player: fixed player can fly after respawn

start.sh
OCD, so yeah.
php7 directory #blameshoghi
=> Remove PHP Version from start.sh notice
