pmmp/PocketMine-MP

src/pocketmine/block/Flowable.php
src/pocketmine/block/WaterLily.php

Standing on top of a lily pad for roughly 5 seconds currently causes players to be kicked for flying.
- Changed Flowable to return null when _recalculating_ bounding boxes.
- Fixed lily pad bounding box (1/64 tall, #blamemojang for making it different in PE)
- Removed some redundant properties (already in parent class or not needed/incorrect)
Walked on top of lily pads, the bug no longer occurs. Tested with various other flowables and found no issues.

Fixed kicked for flying when walking on lily pads

---

src/pocketmine/command/CommandReader.php

Global variables are thread-local. Calling getopt() in a thread will attempt to retrieve the arguments of the thread, _not_ the parent process. This PR fixes that by checking command-line arguments in the thread constructor instead of in the thread's run() method.

Fix --disable-readline command-line option does not work, close #34

---

src/pocketmine/Player.php

As of 0.16, when a player highlights (right-click/tap) an entity, the client starts spamming InteractPackets with an action of 4. The server checks that it's not a right-click, and assumes it's left-click. Now the server only processes it as an attack when the action is 1 (left-click)

Improved action check for InteractPacket

---

src/pocketmine/PocketMine.php
src/pocketmine/utils/ServerKiller.php

Currently the ServerKiller is totally useless due to a logical fail which ensures that the condition for killing the server is never met. It is _also_ only started AFTER everything _except_ the logger thread is closed, which is totally useless since it's almost always one of the other threads that hangs, for example Console thread on Windows.
This pull request starts the ServerKiller thread _before_ other thread shutdown is requested, so that if any of those threads fail to stop the server will commit suicide as expected. This also fixes an issue with the server taking an eternity to stop even after all other threads have exited, because the process will not exit until the timer on the ServerKiller runs out.

Fix ServerKiller and make it less useless

---

src/pocketmine/Player.php

Currently clicking on fire to put it out makes the fire _seem_ to disappear, but will still set fire to any players that walk through the place where the fire used to be. This is because the client sends what is currently known as ACTION_START_BREAK when clicking on fire, but does not send ACTION_ABORT_BREAK when letting off the click. This means that the lastBreak timer does not get reset and subsequent attempts to put fire out will fail until the player does some other action which causes lastBreak to be reset.
This pull request fixes the bug by breaking from the case statement before the timer is set if the player clicks on a block with fire attached.
This has been tested and confirmed to work with fire in creative and survival.

Fixed clicking on fire to extinguish it

---

src/pocketmine/block/Ladder.php

Possible fix for #22 - I cannot reproduce the issue since making this change, although since I don't know what exactly caused the issue to begin with I can't say for sure.
This is in accordance with the (Ladder wiki page)[http://minecraft.gamepedia.com/Ladder#History], which states that (for PC at least) the ladder bounding box is 3/16 of a block wide. It appears to be the same in PE also.

Increase ladder bounding box to 3/16, fix kicked for flying when sneaking on ladders

---

src/pocketmine/MemoryManager.php

This fixes the spam of
```
Warning: sprintf(): Too few arguments in /Users/Tim/Desktop/Pocket_Server/src/pocketmine/MemoryManager.php on line 326
Warning: sprintf(): Too few arguments in /Users/Tim/Desktop/Pocket_Server/src/pocketmine/MemoryManager.php on line 326
Warning: sprintf(): Too few arguments in /Users/Tim/Desktop/Pocket_Server/src/pocketmine/MemoryManager.php on line 326
Warning: sprintf(): Too few arguments in /Users/Tim/Desktop/Pocket_Server/src/pocketmine/MemoryManager.php on line 326
Warning: sprintf(): Too few arguments in /Users/Tim/Desktop/Pocket_Server/src/pocketmine/MemoryManager.php on line 326
Warning: sprintf(): Too few arguments in /Users/Tim/Desktop/Pocket_Server/src/pocketmine/MemoryManager.php on line 326
Warning: sprintf(): Too few arguments in …
```

MemoryManager: Fix sprint too less arguments if $from contains %x

---

src/pocketmine/level/Level.php

If you break/place a block, or force a blockLightUpdate for example at y=3 it will eventually try looking below y=0, which doesn’t make sense and throws exceptions because it can’t find the sub chunk. This issue probably existed for ages, just no exceptions where thrown.

Fix blocklight near y0

---

src/pocketmine/command/defaults/EffectCommand.php
src/pocketmine/entity/Effect.php
src/pocketmine/entity/Entity.php

Because amplifiers are stored as ByteTags and read back from storage as signed, anything over 128 would become a negative amplifier and cause a crash next time the player joined.
- /effect command is now capped to adding effects in the range 0-255
- Fixed amplifiers being read as negative.
This will require translation updates to ensure that force-language and the console work correctly.

Fixed effect amplifier overflow crash, close #147

---

src/pocketmine/network/RakLibInterface.php

Cherry-picked from @PrimusLV 's PR to the old repository (PocketMine/PocketMine-MP#4131)
I have tested this and confirmed it works.
This removes all trailing slashes from the end of the server name, which might break some formatting. An alternative, slightly hackier way to do this was proposed [here](https://github.com/PocketMine/PocketMine-MP/issues/4083#issuecomment-200920496). This does in fact work well.

Fix trailing slashes in MOTD breaks server list, close #153

---

src/pocketmine/block/Obsidian.php

Fixes having to break obsidian twice to mine it.
Adjust hardness value to match Pocket Edition, which for some reason has a lower hardness than PC.

Fix instabreak anti-cheat false positive on obsidian broken

---

src/pocketmine/PocketMine.php
src/pocketmine/command/CommandReader.php

Re-implemented the Command Reader to fix the issue described in #25.
This pull changes the behaviour of the Command Reader stdin stream to be blocking by default, which is better for performance than the original method of querying the stream every 0.01 seconds. It now uses `stream_select` to poll the status of the stream to check if there have been any changes before entering a blocking stream read. This works flawlessly on most regular systems, including in Powershell and CMD on Windows.
This PR also adds auto-detection for fifo piped input. This was necessary because most people use MinTTY as a console for Windows servers, which is essentially a fifo pipe, not an actual console. `stream_select` always returns 1 for fifo pipes, which causes Windows servers under MinTTY to end up in a …

Re-implemented CommandReader, fixed CommandReader hanging on shutdown, close #25

---

src/pocketmine/inventory/PlayerInventory.php
src/pocketmine/item/Food.php

This pull request fixes issues with plugins such as Slapper. Human entities would crash when getting near entities, due to $entity->getServer() not being a defined method. Instead I've replaced it with getHolder and getLevel in order to be able to get the server.

Fixes sendHeldItem to stop crashes when executing.

---

src/pocketmine/level/Level.php
src/pocketmine/level/Position.php
src/pocketmine/level/WeakPosition.php

Should highlight the real cause of #156 .
- Added `Level->isClosed()` method and related properties to allow detecting if a level has been unloaded
- `Position->getLevel()` now checks if its target Level has been unloaded, and if so destroys the reference before returning anything.
- `Position->setLevel()` will now check if the supplied Level object is usable before setting it, and throw an exception if the Level is closed.

Better guards against Positions leaking unloaded Level objects

---

src/pocketmine/Player.php

Sends an empty chunk column when unloading old-world chunks to clear the column client-side. Note this isn't always foolproof, since PocketMine's tracking of chunks loaded by players is bad and inaccurate. This will be improved in the future (#262). It does however work in most cases.

Added a hack for multiworld chunk bug

---

src/pocketmine/Player.php
src/pocketmine/utils/Binary.php
src/pocketmine/utils/BinaryStream.php

Fixed myriad movement-checking bugs:
- fixed ladders, close #22 
- fixed auto-jump pull-backs
- fixed pull-backs flying up/down walls
- fixed pull-backs walking _along_ walls
- fixed all known spectator mode pull-back issues (flying up/down pull-backs)
- fixed placing blocks in front of self sometimes vanish
- fixed most known cases of "player moved wrongly!" (does not include stairs, due to stairs bounding boxes actually being wrong (TODO))
A floating-point accuracy has been added to Binary float reading methods. Network Vec3s are now decoded and rounded to an accuracy of 4 decimal places.
Closes #258 , see that for details.
Close #264

Fix most movement-check false-positives and many position bugs

---

src/pocketmine/Player.php

Obsoletes #206 
This solution is _somewhat_ more effective than the referenced one above. Since multiple TextPackets sent in the space of 1 tick cause dupes of later messages, this _mostly_ alleviates the issue by queuing the messages up and sending them all in one packet on the next available opportunity.
This does not completely resolve the issue though. This only squashes `raw` messages into a single packet, so if, for example, a `translation` and a `raw` are sent in the same tick, like they are in the /help command (header uses translation, entries use raw), then the top messages will still be duplicated.
This does however completely eliminate the /status output issue and mostly eliminates /help issues apart from the one mentioned above.
In the meantime, we wait for Mojang to fix this …

Workaround for chat duplication. TODO: Revert this

---

src/pocketmine/CrashDump.php

Does as title says, I'm sure many people will find this useful.
Once I had a bug that would crash the server every couple seconds, it ended making tons of crash dumps making it hard to even begin to transfer files without freezing my sftp client. This will prevent such a situation and is more organized.

Moved crash dumps to a separate folder

---

src/pocketmine/block/SeaLantern.php

Changed Sea Lantern from extending Solid to extending Transparent, like
GlowingObsidian and Glowstone, so that lighting works properly.

Sea Lantern Lighting Bug

---

src/pocketmine/MemoryManager.php

"[Dump] After the memory dump is done, the server might crash"
With that said, it should not shutdown.

Remove shutdown after memory dump.

---

src/pocketmine/Player.php

When `Level->setChunk()` is called by anything, `ChunkLoader->onChunkChanged()` should be called for any attached loaders. This is _supposed_ to trigger a chunk resend for players, but currently PocketMine-MP sticks the load request into a load queue that for the most part is overwritten every second.
This pull request fixes the issue by removing the specified chunk from the player's index of usedChunks, which will cause the server to automatically resend that chunk next time a chunk order is made.

Fixed half-trees on chunk boundaries, possibly fixed #265

---

src/pocketmine/level/generator/normal/biome/ForestBiome.php
src/pocketmine/level/generator/normal/biome/MountainsBiome.php

This Pull Request fixes two very minor things. One of which being the temperature of the birch biome. The correct value can be found here: http://minecraftpc.wikia.com/wiki/Birch_Forest. Furthermore, this pull request fixes temperature being set twice, while one of these should be rainfall, not temperature.

Fixed wrong temperature and temperature -> rainfall

---

src/pocketmine/command/defaults/GamemodeCommand.php

Shows the correct message ingame but not in the console.
PocketMine doesn't handle the translation for gamemode changes, MCPE
does. No idea why but it requires the second and third parameter....
```
commands.gamemode.success.other=Set %2$s's game mode to %3$s
commands.gamemode.success.self=Set own game mode to %3$s
```
To solve the problem we have to change the language files and let
PocketMine-MP translate it.

Partial fix for #83

---

src/pocketmine/level/Level.php
src/pocketmine/level/format/io/leveldb/LevelDB.php
src/pocketmine/level/format/io/region/McRegion.php

Should (hopefully) highlight what's going on with the big dirty holes in some generated maps.

Throw exception when attempting to save a non-generated chunk

---

src/pocketmine/permission/DefaultPermissions.php

Registers `pocketmine.command.transferserver` under `pocketmine.command` with default level `DEFAULT_OP`.

Fixed missing permission registration in in #355

---

src/pocketmine/Server.php
src/pocketmine/entity/Entity.php
src/pocketmine/entity/Living.php
src/pocketmine/entity/Squid.php
src/pocketmine/event/entity/EntityDamageByBlockEvent.php
src/pocketmine/event/entity/EntityDamageByChildEntityEvent.php
src/pocketmine/event/entity/EntityDamageByEntityEvent.php
src/pocketmine/event/entity/EntityDamageEvent.php

This issue is critical on big PvP servers.
Entities hold a reference to an EntityDamageEvent which details their last damage cause. This is problematic for damage by entities, because entities may be killed, or in the case of players they may quit. This causes those referenced objects to leak. This is commonly seen on large PvP servers with lots of players.
The memory consumed by referenced players would have been a rather large amount before 4f27bce5b34a9e2cbbca0b862761b629270e7fe7. While that commit alleviates general Player leaks by destroying large NBT object trees, it merely reduces the impact of the issue, and does not fix it.
This is not a magical WOWy-style leak fix, it will not magically fix all your issues. You'll probably still see issues after this PR has been merged, as this …

Use entity IDs in EntityDamageByEntityEvents, fixed memory leaks related to PvP/PvE/PvM

---

src/pocketmine/CrashDump.php
src/pocketmine/PocketMine.php
src/pocketmine/Server.php
src/pocketmine/utils/MainLogger.php

- Fixes highest stack frame missing in exception logs
- fixed issues with line breaks and \r in error messages
- Crash dumps with an error will no longer include the `Server->crashDump()` stack frame. (This also means that currently, crashes with errors without xdebug will have no stack trace at all. See #317)

Stop skipping stack frames

---

src/pocketmine/Player.php

So here was the bug:
Whenever the player was damaged down to below 3 - 4 hearts and then if they healed quickly in some way(whether it would be plugin-based, effect-based, etc.) it would drop their health below 0 and kill them client-side, while they would be unaffected server-side.
After extensive testing both with and without this commit using the same techniques and repeating them many times, I've determined this was the bug causing it. As far as I'm aware SetHealthPacket is no longer used, because it's handled by attributes. So this will fix annoying issues with random client-side deaths when at a low enough health, making it for all around better gameplay.

Fix client-side death bug

---

src/pocketmine/block/GlowingObsidian.php
src/pocketmine/block/RedstoneTorch.php
src/pocketmine/block/Torch.php
src/pocketmine/event/LevelTimings.php
src/pocketmine/level/Level.php

Fixed an age-old light calculation bug causing solid blocks to filter their own light. Fixed #375, probably fixed #288
Light spread reduction should be done based on the _target's_ light filter level, not the source.
Fixed issues with light not spreading when a block with some degree of opacity is removed. Light will now correctly spread into previously blocked areas. Close #455

Block light bug fixes

---

src/pocketmine/Server.php

As per @Sandertv 's issue, this will provide clarification as to what is actually happening when something unintentionally serializes a referenced Server object instead of a confuzzling `Serialization of Closure is not allowed` exception.

Throw an exception when something attempts to serialize Server

---

src/pocketmine/block/Lava.php
src/pocketmine/block/Liquid.php
src/pocketmine/block/Water.php
src/pocketmine/level/Level.php

Fixes: #251, PocketMine/PocketMine-MP#3752
Obsoletes: PocketMine/PocketMine-MP#4200, PocketMine/PocketMine-MP#4057, PocketMine/PocketMine-MP#3806, PocketMine/PocketMine-MP#3763, PocketMine/PocketMine-MP#3762.
This PR adds an extra queue for neighbour block updates. Instead of directly updating blocks when a block is changed, neighbour block updates are now queued to be run at the end of the tick.
@PEMapModder 's original suggested solution [here](https://github.com/PocketMine/PocketMine-MP/issues/3752#issuecomment-164487640) would have worked, except for the issue of plugin events, and also the issue that affected blocks would have needed to handle the scheduled update, which is wrong. This  pull request caters for all possibilities of such recursion without breaking plugin events.

Fixed block update recursion issues

---

src/pocketmine/PocketMine.php

It's already called in Memory Manager.. also it makes more sense to call it in memory manager to keep the code clean.

Fixed double gc_enable call

---

src/pocketmine/utils/Config.php

Resolves #516
Closes #517 
Example:
```php
$config = new Config("path/to.json", Config::JSON);
$config->enableJsonOption(JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE)->save();
```

Allow custom JSON pretty print options

---

src/pocketmine/command/PluginCommand.php

This pr removes the null check in PluginCommand::setExecutor() because $executor won't be null in any case.
No relevant issues (atleast I think so)
No API changes -> same result as before.
I doubt there will be any performance improvements, no.
Yes, it is fully compatible.
No actions suggested from my side.
You will need a plugin which manually registers a PluginCommand and sets a CommandExecutor for it. Sorry for not including this here.
The result should be, that $this->executor returns the CommandExecutor mentioned before.

Remove redundant null check in PluginCommand

---

src/pocketmine/item/Item.php

If the item does not have a namedtag set, the console warns of this action.
Necessity: so that lores can be set on items having no namedtag.
isset(), as you know, does not return errors while passing variables. It can only return a boolean value.
* Fixes #857
No
No
Supports backwards compatibility as this is just something that was left out probably.
```
$item = Item::get(Item::DIAMOND_SWORD, 0, 1);
$item->setLore(['This lore is', 'sexy :D']);
```
Before: Warning: Creating default object from empty value in /root/pmmp/src/pocketmine/item/Item.php...
Now: [item gets lore set]

Fix "Creating default object from empty value"

---

src/pocketmine/entity/Human.php
src/pocketmine/level/format/Chunk.php

Humans are currently saved to disk even if they have an invalid skin. This causes the server to subsequently always crash when loading the chunk the invalid Human is in.
This PR adds an exception throw before the Entity base constructor is called to prevent humans with invalid skins being saved to disk and handling to prevent such errors with existing saved humans causing server crashes.
- fixes #835 
An exception will now be thrown when attempting to construct a Human without a valid skin and when trying to set an invalid skin on an entity. Exception handling has been added to chunk initialization to ensure that existing invalid humans will not crash the server and will not be saved to disk again next time the chunk is saved.
No issues
```
<?php
/**
* @name TestPlugin
* @api 3.0.0-ALPHA5 …
```

Throw an exception before calling base entity constructor if skin is not set or invalid, close #835 

---

src/pocketmine/level/format/io/region/CorruptedRegionException.php
src/pocketmine/level/format/io/region/McRegion.php
src/pocketmine/level/format/io/region/RegionException.php
src/pocketmine/level/format/io/region/RegionLoader.php

Recently it was brought to my attention, by someone having freeze issues on their server, that corrupted or invalid region files can _really_ mess up your server.
In the process of testing their issue I discovered that the RegionLoader does not impose any checks whatsoever on region file validity. You can feed any random crap into there and PocketMine will attempt to use it.
My test:
- create new anvil world
- cd worlds/world/region
- echo "lelelelelelelelel" > r.0.0.mca
- start the server
- join, teleport to 0 128 0
- server freezes and writes out 60GB worth of crap to disk, machine freezes for about 15 minutes.
The reason for said freeze was due to an invalid location table. Region files begin with an 8192-byte header, the first 4096 bytes of which are chunk locations. The first 3 bytes …

Added safety checks for region file validity

---

src/pocketmine/Player.php

Item frames are one of the many essentials that contribute to decoration. In PocketMine-MP, there's no way to stop players from triggering ItemFrameDropItemPacket (other than using DataPacketReceiveEvent, of course; which is like the worst-but-the-only-possible decision).
To make it a possibility to cancel ItemFrameDropItemPacket from being triggered, calling PlayerInteractEvent would be a suitable fix.
None.
I don't think so, as this can be considered as a "fix".
ItemFrameDropItemPacket now triggers PlayerInteractEvent.
Compatible.
None.
The following code will stop ItemFrames from dropping the item.
```
public function onInteract(PlayerInteractEvent $event){
if(
$event->getBlock()->getId() === \pocketmine\block\BlockIds::ITEM_FRAME_BLOCK and
$event->getAction() === …
```

Call PlayerInteractEvent (ItemFrameDropItemPacket)

---

src/pocketmine/Achievement.php
src/pocketmine/Server.php

On some languages, there is a small issue on colored message.
Example:
In this example, italic is color.
If there's a message Testing _{%0}_ (English), it'll be shown as Bla _{%0} Hi_ (Some languages).
So this pull request fixes it.
No
No
Yes

Fix issue with colored message on some languages

---

.gitmodules
src/pocketmine/scheduler/AsyncPool.php
src/pocketmine/scheduler/AsyncTask.php
tests/travis.sh

AsyncTask objects were not being correctly collected after completion, causing the server to leak memory if async tasks were used frequently. This was a major show-stopper for stuff like asynchronous chunk serialization, and a big problem for plugins such as @SOF3's Hormones.
- AsyncTasks don't leak anymore
A new submodule, [PocketMine-TesterPlugin](https://github.com/pmmp/PocketMine-TesterPlugin), has been added. Currently this plugin only contains a regression test for this particular bug.
However, the plugin can be easily extended to add more tests (TODO).

Fixed AsyncTask memory leaks

---

src/pocketmine/nbt/NBT.php
src/pocketmine/nbt/tag/ByteTag.php

This is correct, but this change is practically guaranteed to break something.
This fixes an issue with inventory where null slot link (-1) is saved as a TAG_Byte but then read back as unsigned (255).

TAG_Byte should always be signed

---

src/pocketmine/network/mcpe/protocol/AddEntityPacket.php
src/pocketmine/network/mcpe/protocol/AvailableCommandsPacket.php
src/pocketmine/network/mcpe/protocol/ContainerSetSlotPacket.php
src/pocketmine/network/mcpe/protocol/DataPacket.php
src/pocketmine/network/mcpe/protocol/EntityEventPacket.php
src/pocketmine/network/mcpe/protocol/MovePlayerPacket.php
src/pocketmine/utils/Binary.php
src/pocketmine/utils/BinaryStream.php

It's critical to the functionality of the server that network sent data is always valid. This PR cleans up some Binary methods, adds documentation, and most importantly adds strict types for packets and Binary methods.
This will help highlight issues when a required field is missing from a packet (as it will default to NULL and raise a TypeError). This is now particularly important for plugins which use packets when packet field names change (such as AddEntityPacket's `eid` into `entityRuntimeId`) as this will now crash loudly to indicate when the developer is doing something stupid, instead of silently interpreting NULL as 0, an empty string, or whatever else.
Strict types have been enabled on Binary and DataPacket methods. This prevents accidental use of uninitialized/undefined/null …

Binary strict types

---

src/pocketmine/nbt/tag/ListTag.php

Empty list tags should (as of Minecraft 1.10 or thereabouts) have a tag type of TAG_End. They should certainly not be `null`. Due to weak types this previously caused a silent cast to `0`, which concealed this issue.
fixes #972 
fixed some unexpected behaviour
```
$item = Item::get(Item::APPLE, 0, 1);
$item->setNamedTag(new CompoundTag("", [
new ListTag("idk", [])
]));
```
Previously to this PR, this code would cause the issue described in #962. This issue no longer occurs with the changes in this PR.

Fixed type of empty ListTags and removed some undefined behaviour

---

src/pocketmine/Server.php

Previously, creating an entity on plugin enable would throw an error because Server::getTick() returned null
Set a default value of 0 for Server::$tickCounter

Set a default value 0 for tick counter

---

src/pocketmine/level/ChunkManager.php
src/pocketmine/level/Explosion.php
src/pocketmine/level/Level.php
src/pocketmine/level/SimpleChunkManager.php
src/pocketmine/level/generator/GeneratorRegisterTask.php
src/pocketmine/level/light/LightUpdate.php

These masks produced many unexpected behaviours relating to Y coordinates out of bounds, like #914.
This PR carries changes required to fix this issue, along with several others. Adding an exception throw for out-of-bounds Y coordinates for block hashes uncovered several wraparound problems, such as:
- Flying below y=0 would cause block collision checks for blocks up at y=~250
- Breaking blocks at y=0 would trigger block updates at the top of the map.
This may also cause other crashy issues which I haven't identified yet, so this needs careful testing before merging.
- fixes #914
- Added `addToCache` parameter to `Level->getBlock()` to allow plugin developers to choose to not cache the returned block object if they are making frequent requests to the method. This may mitigate issues with …

Removed masks for Y coordinates, throw exception for block hash Y out of bounds, fixed #914

---

src/pocketmine/Player.php
src/pocketmine/entity/Entity.php
src/pocketmine/entity/Living.php

- ~fix (maybe) #1143 (unconfirmed, needs more testing)~
- fix #1106 
- fix #955
- fix #530 
- fix one issue in #262 (chunks order multiple times on join)
PlayerRespawnEvent is no longer called on player join. I consider this to be unexpected behaviour and as such removed it (if you want to spawn the player in a different place, you can teleport them during PlayerJoinEvent).
- fixed bugs noted above
- teleport mechanism is no longer used for player spawning
- removed delayed-teleport system as it is no longer necessary and in most cases just causes more bugs due to clients dropping distant chunks
Lightly tested, seen to fix bugs, needs more testing.

Fixed chunks not loading when respawning and some minor spawn sequence cleanup

---

src/pocketmine/network/mcpe/protocol/ExplodePacket.php

Original error was:
`[12:25:56] [Server thread/CRITICAL]: TypeError: "Argument 1 passed to pocketmine\network\mcpe\protocol\DataPacket::putSignedBlockPosition() must be of the type integer, float given, called in /home/mrgenga/mcpm/src/pocketmine/network/mcpe/protocol/ExplodePacket.php on line 65" (EXCEPTION) in "src/pocketmine/network/mcpe/protocol/DataPacket" at line 350`
This PR fixed it
I relaunched same code and it worked without any errors.

Fix some type errors on custom ExplodePacket use

---

src/pocketmine/Player.php
src/pocketmine/event/player/PlayerQuitEvent.php

There was no way to do this before. I don't believe plugins should be able to modify the reason though. That can be changed though if requested.
This allows the possibility for plugins to track how players leave the server.

Ability to get a players quit reason

---

src/pocketmine/level/Level.php

This should not need to be cleared after 768 batched packets are cached since cached chunks are automatically removed from cache when the actual chunk unloads.
At worst, memory manager will clear the cache by force if the user correctly set his/hers memory limits, though chunk cache itself does not use much memory.
Changes:
- Stop clearing cache after the array meets a size threshold of 768 packets.
- Renamed the $full parameter to $force because it sounds more accurate.

Stop clearing chunk cache after 768 batched packets are cached.

---

src/pocketmine/block/Block.php
src/pocketmine/block/WoodenSlab.php
src/pocketmine/level/Level.php

Since I screwed up the fix for this the first time, being more careful this time.
fixes #145
- added method `Block->canBePlacedAt(Block, Vector3)`
- placing slabs in half-gaps now works as expected
confirmed that this fixes #145, and does not recreate #1314 , but this required more code to fix than anticipated, so there might be other issues that I haven't spotted. Please test and review.

Fix #145, take 2 (slab placement in half gaps doesn't work)

---

src/pocketmine/MemoryManager.php

This function did not work correctly before due to skewed logic. This should be the correct behavior.

Fixed canUseChunkCache() logic

---

src/pocketmine/Player.php

Worlds with peaceful difficulty not allows players to hit themself. 
Now peaceful difficulty allows PvP.

Peaceful difficulty allows PvP

---

src/pocketmine/level/Explosion.php

Prior to the commit below, blocks would be removed but any tiles attached to the block would remain (#1450).
* Fixes #1450
Disclaimer: This does not fix tiles that have not been removed by previous explosions, you should use a plugin to achieve this.
None – it's a pretty straightforward solution.

Fix for explosions not removing tiles

---

src/pocketmine/Player.php
src/pocketmine/entity/Entity.php
src/pocketmine/entity/FallingSand.php
src/pocketmine/entity/Item.php
src/pocketmine/entity/PrimedTNT.php
src/pocketmine/entity/projectile/Arrow.php
src/pocketmine/entity/projectile/Projectile.php
src/pocketmine/entity/projectile/Throwable.php
src/pocketmine/item/Bow.php
src/pocketmine/item/ProjectileItem.php

Historically, there was a memory leak which occurred on chunk unload, due to entities creating drops when kill()ed, which happened when their chunks were unloaded. This made clear that an alternative way to delete entities was needed, which gave rise to usages of close() instead of kill().
The problem with this is that close() is nuclear, and calling it midway through an Entity's tick update would cause following code (none the wiser that the entity was closed) to try to access things like the entity's Level and cause an exception to be thrown.
This PR adds a new method `Entity->flagForDespawn()`, which flags an entity as needing to be deleted on the next tick. This allows entities to be scheduled for deletion without the problem of death animations or dropping items, and without the …

Fixed misuse of kill() and close() when deleting entities

---

src/pocketmine/Player.php

Fixed saving of data that did not work before, because the data was saved before the call to PlayerQuitEvent
Fixed https://github.com/pmmp/PocketMine-MP/issues/1543
Completely tested and everything works fine!

Fixed save player data after PlayerQuitEvent

---

src/pocketmine/entity/Living.php

Before, this function would set the Player's air supply, but not the maximum air supply, which the function is intended to do.
Nothing
Nothing
The function now sets the maximum air supply instead of air supply.
This is backwards compatible.
```php
$player->setMaxAirSupplyTicks(440);
```
Result: Player gets 1 extra air bubble, but it isn't set as 11 bubbles maxed (each bubble is 2 seconds or 40 ticks), and you will lose the bubble and not gain it back.
```php
$player->setMaxAirSupplyTicks(440);
```
Result: Player gets 1 extra air bubble and is set as 11 bubbles (each bubble is 2 seconds or 40 ticks) maxed, and you can gain it back after getting out the water and back in.

Fixed setMaxAirSupplyTicks()

---

src/pocketmine/entity/Effect.php
src/pocketmine/entity/Living.php

When these effects were cancelled, they were still added/removed as active effects server-side. This caused bugs such as #1767 .
#141 introduced the defective code.
cancelling these events now works as expected (in theory)
There is a problem with the behaviour when EntityEffectRemoveEvent is cancelled due to the effect duration becoming zero, which would result in the duration consequently becoming negative and causing a crash. This is a relevant issue but a separate bug from the one this PR is targeted at.
TBD

Fixed broken logic in EntityEffectEvents

---

src/pocketmine/Player.php

See https://github.com/pmmp/PocketMine-MP/issues/1831
`PlayerPreLoginEvent` will be called before check `BanList` and `WhiteList`
This PR should preserve 100% backward-compatibility
```
public function onPlayerPreLoginEvent(PlayerPreLoginEvent $event)
{
$player = $event->getPlayer();
if ($player->isBanned() && $player->hasPermission("ban.exempt")) {
$player->setBanned(false);
}
}
```

Fixed wrong execution PlayerPreLoginEvent close #1831

---

src/pocketmine/Player.php

This fixes the interaction bug described in #983 .
Previously this checked to make sure that the player could interact with the specified block based on their current yaw (no more than 90 degrees either side). This works relatively fine when using crosshairs, but presents problems when using mobile touch controls for mining and placing blocks, since they allow touching blocks which are behind the player.
This PR changes the direction check to also take pitch into account when doing direction checks. This means that the range of clickable blocks will now rotate on the Y axis when the player turns their head, which means they can now legally touch blocks "behind" themselves within certain bounds (again, 90 degrees either way).
fixes #983 
Direction check now works correctly and does not …

Fix direction checking for player interactions, close #983

---

src/pocketmine/block/TNT.php

The `fuse` parameter to `TNT#ignite` can never be used. Currently it sets the NBT as a byte, however here:
https://github.com/pmmp/PocketMine-MP/blob/master/src/pocketmine/entity/PrimedTNT.php#L57-L61
it's retrieved as a short, meaning there's no valid tag and it defaults to the 80 tick fuse.
Not aware of any
nuthin'
Explosions lighting TNT blocks will explode with a fuse of `mt_rand(10, 30)` instead of 80, which is intended.
No issues, actually FIXES something lol
nah
Without this TNT chains explode 80 ticks apart from each other, with it's much faster and not regular at all.
lol sorry for this pr to fix one tiny line

Fix TNT#ignite fuse

---

src/pocketmine/entity/Effect.php
src/pocketmine/entity/Entity.php

Many plugins make use of `Entity::setDataFlag(Entity::DATA_FLAGS, Entity::DATA_FLAG_INVISIBLE, bool)` function. This commit adds a short-hand for the functions, just like some other API functions (`Entity::isSprinting()`, `Entity::setSprinting()`, `Entity::isImmobile()`, `Entity::setImmobile()` etc...).
Added API methods
`Entity::isInvisible()`: Returns whether entity is invisible.
`Entity::setInvisible()`: Toggle entity's visibility.
A simple invisible toggler:
```
/** @var Entity $player */
$isInvis = $player->isInvisible();
$player->setInvisible(!$isInvis);
$player->sendMessage("You are now " . ($player->isInvisible() ? "invisible" : "visible") . ".");
```

Add API methods: Entity::isInvisible(), Entity::setInvisible()

---

src/pocketmine/entity/projectile/Projectile.php

This PR fixes an issue with `Projectile::setOwningEntity()` being called before `Entity::$propertyManager` gets declared.
* Fixes #1942 
Previously, launching projectiles with $shootingEntity (param3) declared would result in an error due to `Entity::$propertyManager` not yet being declared. This can been tested by launching a snowball before and after this code shifting.

Fix projectiles throwing errors on launching, fix #1942

---

src/pocketmine/Player.php
src/pocketmine/entity/Human.php

Since the armor-playerinventory split-up in https://github.com/pmmp/PocketMine-MP/commit/6543d969102b6ce761717073fdd858467217b876, armor contents weren't dropping. This commit restores back the return values of `Human::getDrops()` to contain armor contents and Player's armor inventory to get cleared on death (if keepInventory is enabled).
Death while wearing armor results in armor contents being dropped. This can also be tested by dumping `Human::getDrops()` to check whether it contains the contents from ArmorInventory.
Here's a dump of the following:
https://pastebin.com/fG1pvnV7

Fixed armor not dropping

---

src/pocketmine/Player.php
src/pocketmine/entity/Entity.php

This fixes exploits related to #1567 by calling respawn logic on join when the player has zero health.
This is a shitty fix and doesn't solve the actual issues described in #1567 (lots of things are still done on respawn that should be done on death), but it's a simple solution for the exploits related to it (respawn logic loophole due to rejoining).
This does not resolve (get lost github) #1567, but it resolves the exploits which people have complained about due to this loophole.
This has been tested with normal punching respawn and also with a ragequit respawn. Both now work as expected.

Player: fix respawning after rage-quit on death

---

src/pocketmine/command/Command.php

If a plugin didn't define a custom permission message for a command $permissionMessage will be null so if you try to use Command::getPermissionMessage() an error will be given.
Fixes the issue explained above
Tested and now doesn't give an error anymore when trying to get a null permission message

Allow Command::getPermissionMessage() to return null

---

src/pocketmine/entity/Human.php

The method **isValidSkin()** needs an update to allow skins of 128x128 pixel.
* Fixes issues in plugins using this this method (e.g. Slapper) when validating skins of this size.
I noticed when creating NBT data from skindata (128x128 pixel) you'll need a ByteArrayTag because a StringTag can't hold a length of 128 * 128 * 4 bytes.
I've tested this change using the Slapper plugin - result can be seen here 😄 :

Human: Add support for 128x128 skins in isValidSkin()

---

src/pocketmine/block/DoubleSlab.php

`DoubleSlab::getName()` concatenates the single slab's name. [Slabs already return their name along with the `Slab` suffix](https://github.com/pmmp/PocketMine-MP/blob/4f8e4f05220ecd56b038204009fbfdfe4a6359e4/src/pocketmine/block/StoneSlab.php#L59). `DoubleSlab` class suffixes the `Slab`-suffixed name by adding another `Slab` making `DoubleStoneSlab::getName()` for example, return `Double Stone Slab Slab`.
This PR removes the "Slab" suffix from DoubleSlabs.
```php
var_dump(Block::get(Block::DOUBLE_STONE_SLAB)->getName());
//Prior to this PR: string("Double Stone Slab Slab")
//With this PR: string("Double Stone Slab")
```

Fix DoubleSlab block name

---

src/pocketmine/inventory/transaction/InventoryTransaction.php

InventoryTransaction uses spl_object_hash twice
Maybe perfomance ;)

Remove double use of spl_object_hash

---

src/pocketmine/plugin/PluginBase.php

`PluginBase::getResources()` now returns the result in an associative array of strings.
Previously, it was a plain linear array containing instances of `SplFileInfo`.
Now, it has string keys, which is the path of the resource file relative to the resources folder.
May affect plugins that expect getResources() to return numeric arrays. However, the key type has never been clearly documented, so it is not considered an API break.
[A search on Poggit](https://poggit.pmmp.io/grepPlugins/2018-05-20-439be3a5b802b571.html) shows that no plugins are relying on the numeric nature of the keys.
Tested.

PluginBase::getResources() returns associative array

---

src/pocketmine/inventory/DoubleChestInventory.php
src/pocketmine/tile/Chest.php

chest pairing really needs rewriting... this code really sucks
This is hacky but fixes #2261 .
- fixed bug described in #2261 
- Paired chest halves now share the same `DoubleChestInventory` instance
rewrite chest pairing... it really, really sucks
has been lightly tested, but I'm wary of merging this directly due to the potential for recursion bugs. @Muqsit would you mind testing this?

Fixed double chest inventory desync issues, closes #2261

---

src/pocketmine/plugin/PluginManager.php

This is quite an interesting bug. If you have
```php
class A{
public function onMove(PlayerMoveEvent $event){} //shouldn't be a handler because this class isn't a Listener
}
class B extends A implements Listener{}
```
then
```php
registerEvents(new B, $plugin);
```
then `A::onMove()` will be registered as an event handler even though `A` is not an instanceof `Listener`.
This was observed by noting that plugins which do something like `extends PluginBase implements Listener` causes `registerEvents()` to try and register `PluginBase` methods as event handlers, which could lead to astonishing behaviour.
None known.
- Methods declared in parent classes of classes implementing `Listener` will not be considered as event handlers unless they themselves implement `Listener`.
If anyone used this …

PluginManager: Skip methods not declared by instanceof Listener when registering handlers

---

src/pocketmine/level/Level.php

I don't care if this matches PC behaviour or not. bugs.mojang.com is full of bug reports about this. Just search for "minecraft spawn protection not working" and you'll see what I mean.
If you want to disable spawn protection, actually disable it. This behaviour is something that most users are not aware of and find astonishing when they discover it.
More than I care to list. Many people have complained about spawn protection inexplicably not working over the years.
If enabled, spawn protection will no longer be disabled when there are no operators.
Consider moving spawn protection to an external plugin.
This is a trivial change and shouldn't need extensive testing.

Level: Make spawn protection non-dependent on op count

---

src/pocketmine/Server.php
src/pocketmine/utils/Config.php

As discussed in #2297:
Honestly I don't see a fit purpose for async saving at all. It should either always be synchronous or always asynchronous, and at the user's own option. However, this isn't currently possible because Config doesn't enable you to get the serialized content without writing it to disk.
Consider the following code:
```php
for($i = 0, $size = $this->getServer()->getAsyncPool()->getSize(); $i < $size; ++$i){
$this->getServer()->getAsyncPool()->submitTask(new class extends AsyncTask{
public function onRun(){
sleep(5);
}
});
}
$config = $this->getConfig();
$config->set("steve", "hi");
$config->save(true);
$config->set("steve", "bye");
$config->save(false);
```
Output:
```yml
---
steve: hi
...
```
Expected output:
```yml
---
steve: bye
...
```
Additionally, if your configs …

Remove async config save

---

src/pocketmine/level/Level.php

For a long time it's been a problem that plugins may unload a level during an event fired during the level's tick. This generally causes instability and crashes due to things having their levels suddenly closed without warning.
This pull request disallows unloading levels during level ticks, and presents clear errors about why this cannot be done.
#1527 
- `Level->unload()` will now throw an `InvalidStateException` if called during a level tick.
This presents changes of behaviour to plugins unloading levels during events. However, since this would usually crash the server anyway, it's not considered to be a big deal.
Provide a way to asynchronously unload a level, since it can't always be done immediately.
TBD

Level: Bail on trying to unload a level during level tick

---

src/pocketmine/plugin/PluginManager.php

The basic principle here is "if you're not expecting it, don't catch it".
Event handlers are **never** supposed to throw exceptions. If they do throw exceptions, it's usually going to one of two things;
1. Broken code producing an error
2. Code triggering (and not catching) a runtime error
Both 1) and 2) boil down to defective code on the part of the event handler, and thus should not be caught by the caller, but instead allowed to crash the server and produce a crashdump.
It's also undesirable to catch unexpected errors here for a few other reasons
- It leaves the owner of the event handler in an unknown, potentially unstable state
- It allows broken code to cause event handlers to spam the logger in events that happen frequently (for example movement handlers)
- It allows the process to …

PluginManager: Stop catching exceptions thrown by event handlers

---

start.cmd
start.ps1
start.sh

This was suggested recently by @TheDeibo. We don't want end users running source-code installations unless they are developers, and developers should know how to boot a source-code installation anyway.
`start.sh`, `start.ps1` and `start.cmd` no longer take note of source-code installations.
Note that in the future, support for running from source-code could be removed altogether (for example if a preprocessing step becomes mandatory).

Remove support for source-code installations from start.* scripts

---

src/pocketmine/Server.php

This is an incremental improvement over 4a6841a5a465c791b512517394241f0ac0b38739. This change works better because it also reduces disk spam of crashdumps.
This will now sleep if the server uptime was less than 120 seconds before crashing. If unattended, this will clamp down on automated crashdump spam. If attended, the user can simply press CTRL+C to abort the process and skip the delay.
If the server crashes with < 120 seconds of uptime, it will now sleep until 120 seconds has passed since the start time.

Force minimum uptime to be >= 120 seconds if the server crashes

---

src/pocketmine/Player.php
src/pocketmine/network/mcpe/PlayerNetworkSessionAdapter.php

This fixes various problems, such as forms not working on PlayerJoinEvent.
This change was already applied on `master` during my great network nuke. This PR is to backport the change to the stable line.
`PlayerJoinEvent` will now only fire when the player sends a `SetLocalPlayerAsInitializedPacket`.

Backport usage of SetLocalPlayerAsInitializedPacket to 3.4

---

src/pocketmine/network/upnp/UPnP.php
src/pocketmine/utils/Internet.php
src/pocketmine/wizard/SetupWizard.php

Internal IP detection is completely broken on every platform except windows. On Windows, it only works when the correct network adapter has highest priority (see #2702 ). Great!!!
This pull request fixes internal IP address detection for IPv4 local-area networks.
fixes #2702 
- added `Internet::getInternalIP()`
- UPnP now works correctly with multiple net interfaces.
- Setup wizard now reports the correct internal IP on 'nix platforms.
I don't know how to test this in an automated fashion, but this has been tested on multiple Windows and Linux devices. Connected vs unconnected state has also been tested.

Fixed internal IP detection

---

src/pocketmine/network/mcpe/protocol/StartGamePacket.php

Regeneration when canceled can appear to regeneration, which isn't right. This PR adds a gamerule hack that prevents the client from making those false hearts appear. Discussed in the [issue](https://github.com/pmmp/PocketMine-MP/issues/2721), it has also been reported to mojang [here](https://bugs.mojang.com/browse/MCPE-20507).
Fixes #2721
No API changes.
No Behavioral (you're welcome for no "u" Dylan ❤️) changes.
Nothing is broken out of this.
This was tested on a server with regeneration canceled and on a server with regeneration enabled. Both work as expected.

Hack for client side regeneration

---

src/pocketmine/block/CocoaBlock.php

Currently you can use bonemeal on cocoa blocks indefinitely. This pull request fixed that behaviour by reducing the count by one after each usage.
No API changes to note.
CocoaBlock->onActivate() now returns true when bonemeal was used successfully.
No concerns regarding backwards compatibility.
No related follow-up.
It was reproduced on the pmmp dev server. The setup is fairly simple:
1. Place jungle wood in the world
2. Attach cocoa on it
3. Try to forcefully grow it using bonemeal
4. Notice you keep your bonemeal using the master branch

Fix bonemeal count not reduced by CocoaBlock

---

src/pocketmine/PocketMine.php

this fixes #2855.
The problem is described briefly in #2855 - it's possible for server data corruption to occur by accessing the same data (in write mode) from two processes simultaneously. While we can't prevent this from happening if the user really wants to be stupid, we can prevent accidents like this from occurring.
Two servers may not use the same datadir at once anymore.
Users very commonly have problems on Linux SSH losing access to their terminals. It could be advantageous to have the server offer a `--kill-zombies` option or similar which can automatically detect and kill lost servers (with appropriate warnings that this might cause data loss).
This has currently been tested on Windows 10 and Ubuntu 16.04.

Acquire exclusive lock on <datadir>/server.lock to avoid data corruption

---

src/pocketmine/entity/Entity.php

The current problem is that a plugin could enter a infinite loop when calling Entity::close in a EntityDespawnEvent.
* Fixes #2876
Entity::close may not fire any additional events when called from inside the EntityDespawnEvent. 
I haven't touched the $closed ordering to fix this issue since it would break the event contract on the entity. That should maybe be done on 4.0 but not on 3.x
Think about reordering close variable state inside Entity::close

Implement a locking variable to circumvent a infinite regression

---

src/pocketmine/Server.php

There should be call strtolower because players data saves in lower case

Fix for Server::hasOfflinePlayerData

---

src/pocketmine/event/Listener.php
src/pocketmine/plugin/PluginManager.php
src/pocketmine/plugin/RegisteredListener.php

Ignoring cancelled events is usually the desired behaviour, and should be the default if undetermined (or casually missed).
In addition, the `@ignoreCancelled` tag has been ambiguous. Some people tend to take the double-negation interpretation of "ignore whether an event is cancelled and fire it anyway" rather than "ignore cancelled events and don't handle it". Calling it `@handleCancelled` removes the ambiguity.
Declaring `@ignoreCancelled` will now trigger error.
Declaring `@handleCancelled` will now cause cancelled events to be handled.
Not declaring `@handleCancelled` (or `@handleCancelled false`) will now cause cancelled events to not be handled. This is a BC break.
All current plugins will no longe rreceive cancelled events unless explicitly declaring `@handleCancelled`.
To be …

Changed ignoreCancelled opt-in to handleCancelled opt-in

---

src/pocketmine/plugin/PluginManager.php

On most filesystems, plugins are loaded in lexical order because that's how the filesystem gives the files to us. This is a problem because it can hide bugs with dependency resolution on specific platforms with this behaviour, while inexplicably breaking on other platforms where the load order is different or undefined.
This change prevents plugins depending on any file yield order by randomizing the order in which plugin files are checked for loadability.

Randomize the order of plugins retrieved from disk, fixes #2945

---

src/pocketmine/entity/Entity.php

While Entity::setNameTagAlwaysVisible() was setting the byte data value, Entity::isNameTagAlwaysVisible() was still returning the unused flag value.
Before this commit:
```php
$entity->setNameTagAlwaysVisible(true);
var_dump($entity->isNameTagAlwaysVisible()); //bool(false)
```
After:
```php
$entity->setNameTagAlwaysVisible(true);
var_dump($entity->isNameTagAlwaysVisible()); //bool(true)
```

Fix Entity::isNameTagAlwaysVisible() was returning the wrong value

---

src/pocketmine/plugin/PluginManager.php

In some circumstances, a plugin that has "loadbefore: AnotherPugin" in its plugin.yml will be loaded after that plugin anyway because of the soft dependencies being overwritten by the ones in plugin.yml at [this line](https://github.com/pmmp/PocketMine-MP/blob/d874be99a693adeaf99de5ccef2b45509a408be2/src/pocketmine/plugin/PluginManager.php#L289)
This PR fixes that issue by merging the soft dependencies declared in plugin.yml with the ones that might have been previously set by the loadbefore directive.
To reproduce the bug described and therefore to test this fix do the following:
- Have three plugins in the server: pluginA, pluginB, pluginC
- Let pluginA depend on pluginC and loadbefore pluginB
- Restart the server multiple times and notice that, without this fix, 1/3 of the times …

Fix loadbefore sometimes not working

---

src/pocketmine/Player.php
src/pocketmine/PocketMine.php
src/pocketmine/Server.php
src/pocketmine/block/Block.php
src/pocketmine/block/Fence.php
src/pocketmine/block/Thin.php
src/pocketmine/command/SimpleCommandMap.php
src/pocketmine/entity/Entity.php
src/pocketmine/entity/Human.php
src/pocketmine/entity/Living.php
src/pocketmine/entity/projectile/SplashPotion.php
src/pocketmine/inventory/ShapelessRecipe.php
src/pocketmine/inventory/transaction/CraftingTransaction.php
src/pocketmine/inventory/transaction/InventoryTransaction.php
src/pocketmine/item/PaintingItem.php
src/pocketmine/level/Level.php
src/pocketmine/level/format/io/leveldb/LevelDB.php
src/pocketmine/permission/BanEntry.php
src/pocketmine/permission/PermissionManager.php
src/pocketmine/tile/Furnace.php
src/pocketmine/utils/Config.php
src/pocketmine/utils/Timezone.php
src/pocketmine/wizard/SetupWizard.php
tests/phpstan/configs/phpstan-bugs.neon

`empty()` is evil.
closes #3202 
This has not been manually tested, but Travis is green.
A new `ignoreErrors` entry was added to `phpstan-bugs.neon` (see https://github.com/phpstan/phpstan/issues/2750).

Remove usages of empty()

---

src/pocketmine/Player.php

When a player in survival mode breaks a block, the item in his hand is immediately overwritten by another one with a different durability. This causes unexpected behavior: if the item the player has in his hand changes during BlockBreakEvent, it will reappear. 
This PR fixes that issue.
Fixes #2010
Checks if the player's item in hand is different before overriding it.
This PR should maintain backwards compatibility.
I made a plugin to clean the inventory when BlockBreakEvent was called and then checked if #2010 was still occurring, it wasn't.
[![Youtube video](https://img.youtube.com/vi/oL_XSPNikzc/0.jpg)](https://www.youtube.com/watch?v=oL_XSPNikzc)

Stop overriding item in hand if it has changed

---

src/pocketmine/Player.php

This PR goes in the same lane as #3345: It makes sure the held item hasn't changed before setting it back to the inventory, preventing unexpected behavior such as items staying in the inventory when a plugin modified it on EntityDamageByEntityEvent.
Fixes #3340 
This PR maintains BC.
#3340 can't be reproduced using this patch.
[![IMAGE ALT TEXT HERE](https://img.youtube.com/vi/2MW4CU1KSnQ/0.jpg)](https://www.youtube.com/watch?v=2MW4CU1KSnQ)

Player: Stop setting held item post entity attack if changed

---

src/pocketmine/network/rcon/RCON.php

This fixes an issue where RCON is unable to start after being abruptly stopped.
1. Start PocketMine-MP server with RCON enabled.
2. Use an RCON client to execute `/stop` on the server.
3. When the server reboots, RCON will be able to bind the socket. Without this PR, RCON will exit with the error below:

Fix RCON socket lingering

---

src/pocketmine/Player.php
src/pocketmine/network/mcpe/NetworkBinaryStream.php
src/pocketmine/network/mcpe/protocol/PlayerListPacket.php
src/pocketmine/network/mcpe/protocol/PlayerSkinPacket.php
src/pocketmine/network/mcpe/protocol/ProtocolInfo.php
src/pocketmine/network/mcpe/protocol/types/PersonaPieceTintColor.php
src/pocketmine/network/mcpe/protocol/types/PersonaSkinPiece.php
src/pocketmine/network/mcpe/protocol/types/SkinData.php

This pull request adds support for the new 1.14.60 update
SkinData now has 4 extra properties, armSize, skinColor, personaPieces, pieceTintColor with a getter for each.
1.14.60 clients can now join
There is no BC breaks
A 1.14.60 client can join the server fine on a clean installation using these changes

1.14.60 support

---

src/pocketmine/Player.php

When developing the 1.14.60 update, I miss typed a variable which can have serious side effects. This pull request fixes the typo.
https://github.com/pmmp/PocketMine-MP/commit/a107ad74048145c1969b2541eb8f053d70337b09#commitcomment-38561123

Used wrong variable to store persona pieces on login

---

src/plugin/DiskResourceProvider.php

`DiskProviderResource::getResource()` suffixes `resources/` to file causing `DiskResourceProvider::getResource("file.txt")` to check for
`plugins/TestPlugin/resources/resources/file.txt`
Crashdump: https://pastebin.com/raw/YYVGJ1QX<br>
Test plugin:
- phar: https://transfer.sh/p4PcJ/ResourceTestPlugin_v0.0.1.phar
- zipped: https://transfer.sh/8E8ze/ResourceTestPlugin.zip
```
ResourceTestPlugin-master/plugin.yml
ResourceTestPlugin-master/resources/test.yml
ResourceTestPlugin-master/src/muqsit/resourcetestplugin/Main.php
```

Fix DiskResourceProvider::getResource() returning null

---

src/network/mcpe/convert/TypeConverter.php

Dragging items from creative inventory into hotbar causes transaction mismatch due to `NetworkInventoryAction::$newItem` being supplied as the `sourceItem` to `CreateItemAction`
* Fixes #3436 
Prior to this, the transaction would be cancelled due to mismatch:
```
[04:18:37.069] [Server thread/DEBUG]: [NetworkSession: MuqsitRayyanXO] Failed to execute inventory transaction: Action pocketmine\inventory\transaction\action\CreateItemAction is not valid in the current transaction
[04:18:37.069] [Server thread/DEBUG]: [NetworkSession: MuqsitRayyanXO] Actions: [{"sourceType":0,"windowId":0,"sourceFlags":0,"inventorySlot":5,"oldItem":{},"newItem":{}},{"sourceType":3,"windowId":null,"sourceFlags":0,"inventorySlot":1,"oldItem":{},"newItem":{}}]
[04:18:37.070] [Server thread/DEBUG]: [NetworkSession: …
```

Fix taking items from creative inventory causing mismatch

---

src/pocketmine/utils/Utils.php
tests/phpstan/configs/phpstan-bugs.neon
tests/phpunit/utils/UtilsTest.php

Doc comments like the following parsed correctly:
```
/**
* @ignoreCancelled
*/
```
but not like this:
```
/** @ignoreCancelled */
```
This pull request fixes this problem.
#3388
`Utils::parseDocComment()` now returns results in more cases.
No BC breaks are expected.
Support `-` and other symbols in tag names (I noticed these wouldn't parse during my work to fix this bug).
New PHPUnit test cases have been added.

Utils: fix parsing of single-line doc comments, closes #3388

---

src/pocketmine/permission/PermissionManager.php

`Timings::$permissionDefaultTimer->stopTiming()` didn't get called, leading to inaccurate timings report. (#3500)

Fix timings calculation bug in PermissionManager

---

src/pocketmine/entity/Living.php

As explained in issue #3170, in neither Minecraft Bedrock nor Java, does the action exist anymore that players can set each other on fire by hitting each other, this PR allows mobs that are on fire to still set players on fire with damage (as that still exists).
Fixes #3170 
Looking at this, the fix could be better, I originally wanted to check if it were an instanceof Monster, however looking at 4.0, that class no longer exists, so I don't want to add the extra burden of dealing with this in 4.0 changes. Ideally, you could actually just remove this if statement in general if you didn't care about mobs, because projectiles are already handled within the [projectile](https://github.com/pmmp/PocketMine-MP/blob/master/src/entity/projectile/Projectile.php#L301-L308) class.
EDIT: 
It seems …

Players no longer burn when hit by other players

---

src/pocketmine/item/Bow.php

In vanilla Minecraft, arrows do not catch fire whilst a player is on fire. This PR removes that intentional behavior, as it does not exist in Java 1.8 or Bedrock.
Fixes #3504
Testing consisted of setting a player on fire, the player does not set the arrow on fire.

Burning players no longer set arrows on fire

---

src/pocketmine/block/Water.php

Removes duplicate call to `Entity::resetFallDistance()` introduced in this commit https://github.com/pmmp/PocketMine-MP/commit/8169803bb49a0b3315915188aeb8650a6c3bda64#diff-cf4efef19226a2cd7efd37f88350b474
(`Entity::resetFallDistance()` is called in Water#L69)
Unsure if the commit referenced above makes this redundant as well: https://github.com/pmmp/PocketMine-MP/blob/stable/src/pocketmine/block/Lava.php#L103

Remove duplicate call to Entity->resetFallDistance()

---

src/utils/RegistryTrait.php

Fixed incorrect strtoupper of incorrect letters on operating systems using languages other than English. 
Like (Stair => STAİR)
```
Error: No such registry member: pocketmine\block\utils\StairShape::STRAIGHT
File: src/utils/RegistryTrait
Line: 102
Type: Error
```

Registry Trait: fix strtoupper error

---

src/pocketmine/block/Cake.php

The PR aims to fix an issue regarding the cake block picking that gives the item with the same block meta value instead of 0.
https://streamable.com/to40zq
No.
No.
Yes.
Obviously it has been tested, I don't think it's necessary to give the demonstration given the simple solution of the problem.

Fixed wrong meta value when pick cake block.

---

src/network/mcpe/protocol/EmoteListPacket.php

In 4.0, a packet processing error occurs when the player applies an emote to a custom skin and tries to connect.
Like this, 
*  EmoteListPacket is now implemented as ServerboundPacket.

EmoteListPacket can be ServerboundPacket

---

src/pocketmine/network/mcpe/protocol/types/SkinData.php

1.16 introduced a new setting, Only Allow Trusted Skins, which replaced all non-trusted skins with a Steve skin. Defaulting this to true will prevent all legacy skins etc. from becoming Steve.
There have been no API changes made
There will be no performance changes, but all skins will now be shown by the client without them having to disable the new setting.
There is no backwards compatibility issues
Joining a clean PMMP server with another player will allow you to see their skin successfully.

Default SkinData::$isVerified to true

---

src/pocketmine/block/Podzol.php

The value of hardness was wrong for the Podzol block resulting in breaking particles not being shown correctly.
No relevant issues.
This PR changes the hardness value for the Podzol block from 2.5 to 0.5. Source: https://minecraft.gamepedia.com/Podzol
I tried breaking blocks of podzol with bare hands both before and after this change. Before the change, the blocks would have been broken before the breaking particles had reached its edges, while after the change they perfectly match client breaking time.

Fix wrong hardness value for Podzol

---

src/pocketmine/entity/Living.php

When a new player would join without this, after commit https://github.com/pmmp/PocketMine-MP/commit/09eb904f6b818756e59325bf71ea72e2e3a12a2b, they would be kicked because there was no default provided for Health.
There isn't much to say about this other than I tried to join after resetting my player data, and it worked fine.

Provide a default for health

---

src/event/player/PlayerDisplayNameChangeEvent.php
src/player/Player.php

This PR aims at providing a way to detect when the display name of a player changes. The display name of the player might be used in variety of places like for setting nicks, in chat, for displaying on scoreboard and the likes. Currently you can't tell if the name was updated or not. 
PM provides the function to change display name so its only fitting for a way to detect name changes as well. Rather than using custom player class to detect name change.
N/A
- Introduced new `PlayerDisplayNameChangeEvent`
- `PlayerDisplayNameChangeEvent->getOldName()`
- `PlayerDisplayNameChangeEvent->getNewName()`
- `PlayerDisplayNameChangeEvent->setNewName()`
- Changes done to `Player::setDisplayName()` to call the event
N/A
N/A
N/A
https://gist.github.com/Ifera/257e1a82f8dc2020e3fe970da92893fb
That gist …

Introduce PlayerDisplayNameChangeEvent

---

src/command/defaults/EnchantCommand.php

Commit https://github.com/pmmp/PocketMine-MP/commit/a01c086481da988ab3409bc399d82f72ed9134ce causes `/enchant` to throw unhandled `\InvalidArgumentException` when supplied an unregistered string enchantment ID.
Prior to this patch:
* Run `/enchant steve aqua_affinity 1` (`aqua_affinity` is not a registered enchantment)
* Server throws `Error: No such registry member: pocketmine\item\enchantment\VanillaEnchantments::AQUA_AFFINITY` (https://pastebin.com/raw/UDqLFC2i)
With this patch:
* Run `/enchant steve aqua_affinity 1`
* An error message is displayed in chat

Handle InvalidArgumentException thrown by VanillaEnchantments::fromString

---

src/pocketmine/inventory/BaseInventory.php

`Inventory->canAddItem()` returns true regardless of the item's max stack size. This causes unexpected behavior when, for example, 4 swords are being checked if they can be added to an inventory that has less than 4 slots.
`N/A`
`Inventory->canAddItem() now checks the item's max stack size too`
`Yes`
`N/A`
I'm not quite sure how I would provide tests for this.

canAddItem(): consider item max stack size

---

src/pocketmine/plugin/PluginDescription.php

I made this pull request to fix an issue with the /version command.
When providing a plugin with an array value in 'author', it would crash, because the array won't be parsed into `authors` property.
To fix this, I've made a check if its an array, if so, the array gets "parsed" into `authors` property, like said above.
- Fixes #3902 
/
/
Everything fine with it.
/
The tests with some plugin which have an array-value in author section went successful.
The `plugin.yml` can look like this:
```yaml
name: "TestPlugin"
version: 1.0.0
description: "Just for testing the API..."
author: ["FirstDev", "SecondDev"]
authors: ["Another", "AndAnother"]
api:
- 3.0.0
main: TestPlugin\TestPlugin
```
Before my fix, the server would crash, now, everything goes well.
The if-case for the grammar with "Author" …

Fixed crash when executing command /version with multiple authors declared in 'author'

---

src/pocketmine/block/BlockToolType.php
src/pocketmine/block/Sponge.php
src/pocketmine/item/Hoe.php

Right now when a hoe is used to break a block, no damage is applied to the hoe. This PR aims to fix that.
#3965 
* Damage is added when the hoe is used
Nope no API changes
Damage is added to a hoe when it is used to break a block. 
No BC break
~~* We probably still need to add the hoe tool to the BlockToolType interface. However, I do not know its value. I assume the values are just random bit values. But I am not sure~~ I added the hoe to the BlockToolType interface
* I don't know the correct damage value for the hoe
Before the changes:
https://file.mohamedelyousfi.be/taRO5/seMADENI98.mp4
After the changes:
https://file.mohamedelyousfi.be/taRO5/SIYOCUzu30.mp4
The "dura" in chat indicates the damage on the item and not the durability.
This is one of my first PR's, so feedback is …

Fix that a hoe gets damage applied to it, when it's used to break a block

---

src/block/TNT.php
src/entity/object/PrimedTNT.php

This PR fixes the issue of the TNT ignite-sound not being broadcasted by the server correctly.
#3952 
The broadcast sound method has been moved to the TNT class AFTER the spawnToAll() method has been called. This way the getViewer() method will be used correctly and the sound will be broadcasted to all the viewers, instead of no one.
You can hear the TNT ignite
See video
https://user-images.githubusercontent.com/40402787/103944544-1953be80-5134-11eb-88ce-aeb83a48c86a.mp4

Fixed TNT broadcasting ignition sound

---

src/pocketmine/event/block/BlockBreakEvent.php
src/pocketmine/network/rcon/RCONInstance.php

Since php 8, the following error occurs on `stable` and `master` branches
```bash
[04:50:30] [Server thread/CRITICAL]: ErrorException: "Required parameter $drops follows optional parameter $instaBreak" (EXCEPTION) in "pmsrc/src/pocketmine/event/block/BlockBreakEvent" at line 51
[04:50:30] [Server thread/CRITICAL]: #0 pmsrc/vendor/composer/ClassLoader(444): pocketmine\utils\Utils::errorExceptionHandler(integer 8192, string[64] Required parameter $drops follows optional parameter $instaBreak, string[105] phar:///home/pmmp/PocketMine-MP.phar/src/pocketmine/event/, integer 51)
[04:50:30] [Server thread/CRITICAL]: #1 pmsrc/vendor/composer/ClassLoader(444): include()
[04:50:30] [Server thread/CRITICAL]: #2 pmsrc/vendor/composer/ClassLoader(322): Composer\Autoload\includeFile(string[127] …
```

Fix deprecated required variable $drops to optional

---

src/pocketmine/Player.php

a lot of people have complained before that they get kicked for flight while the movement cheats is enabled
now it will cancel the event instead of kicking the player

instead of kicking player for toggling flight cancel the event

---

src/pocketmine/Player.php

as explained in #4130 the server depend on ContainerClosePacket to call InventoryCloseEvent, this is problematic cause it will break plugins depending on that event if the client didn't send ContainerClosePacket.
* Fixes #4130 
-->
now InventoryCloseEvent will be called whenever the inventory is closed from the server side

call InventoryCloseEvent on removeWindow()

---

composer.json
composer.lock

New version of `adhocore/json-comment` is available
none
none
no BC breaks
none
> https://github.com/pmmp/PocketMine-MP/pull/4146/checks

Bump adhocore/json-comment, new version strips trailing comma as well

---

src/pocketmine/level/generator/normal/Normal.php

As of now the BiomeSelector class has a bug that prevents mountains from generating in the world, left unfixed for several concerns about a possible fix being inaccurate. This pull request attempts to create a decent fix for this issue
This PR message is still currently a WIP 
No relevant issues
None
Mountains and Small Mountains now generate in the world naturally
No backwards incompatibility, this merely changes the terrain generator, which is entirely server side and currently untouchable by plugins
Unlikely to require any follow up after merge
Generated mountains:

Fixed bug that never lets mountainous terrain generate

---

src/block/DragonEgg.php

This PR aims to solve https://github.com/pmmp/PocketMine-MP/issues/4179
Dragon eggs should be broken if the player is in gamemode c
* Fixes #4179 
None.
Dragon eggs don't teleport when they're attacked when the player is in creative
All the changes are BC
Nope
https://streamable.com/c5kj1v (note that I am switching between right and left click in the video)

Fix dragon egg teleporting in creative

---

src/pocketmine/item/Item.php
tests/phpstan/configs/l8-baseline.neon
tests/phpunit/item/ItemTest.php

As reported in #4144, Item->removeEnchantment() doesn't remove the "ench" tag when there are no more enchantments left on the item.
This PR fixes this issue by checking if, after the enchantment has been removed, there are no other ones left and acting accordingly.
* Fixes #4144 
None
Now the shining effect won't be shown on items which don't have any enchantments but previously did.
Yes
None
I added a phpunit test to verify that the "ench" tag is being correctly removed when there is the need to do so.
I also confirmed that the reproducing code provided in the issue does not reproduce anymore.

Remove "ench" tag when all enchantments are removed from an item (Fixes #4144)

---

src/pocketmine/network/mcpe/protocol/SetDisplayObjectivePacket.php

There were no documented constants for some of the fields in SetDisplayObjectivePacket - these being displaySlot and sortOrder (which are two of the fields that matter in terms of what the client sees). This PR adds constants DISPLAY_SLOT_LIST, DISPLAY_SLOT_SIDEBAR and DISPLAY_SLOT_BELOW_NAME, as well as SORT_ORDER_ASCENDING and SORT_ORDER_DESCENDING.
Five new constants are now available in SetDisplayObjectivePacket - three for the displaySlot field and two for the sortOrder field.
There are no observable behavioral changes.
There are no backwards compatibility problems coming from these minor additions.
N/A

SetDisplayObjectivePacket: added missing constants

---

src/inventory/InventoryHelpersTrait.php
tests/phpunit/inventory/BaseInventoryTest.php

Fixed a bug that prevented adding more than 64 items to the inventory even if there was enough space when the following code was executed.
```php
$player->getInventory()->addItem(VanillaItems::APPLE()->setCount(100));
```

InventoryHelpersTrait::AddItem() cannot add items with a count greater than maxstack

---

src/pocketmine/Player.php

When the player disconnect, the items in crafting grid and cursor inventory were returned to the player's inventory before PlayerQuitEvent.  
* Fixes #4318
* Fixes #4315

Fix item losing when player disconnect

---

src/network/mcpe/InventoryManager.php

Offhand slots sometimes ignore Inventory Slot Packets.
* Fix #4231 
Send InventoryContentPacket as a workaround.
https://user-images.githubusercontent.com/76860328/128989052-edf5584e-eef4-4803-b312-219732f14299.mp4

Workaround for offhand sync

---

src/block/BlockFactory.php

This pull request fixes `VanillaBlocks::MOB_HEAD()->asItem()` returning an item with the original `mob_head_block` ID instead of the correct item ID, causing an incorrect render client-side, and the wrong skull type to be used when placed.
Give a skull to the player, even with a different skull type, for example... a player:
`VanillaBlocks::MOB_HEAD()->setSkullType(SkullType::PLAYER())->asItem()`
What would be received is: 
Expected item:

Use the correct Skull Item ID

---

src/entity/object/ItemEntity.php
src/entity/projectile/Arrow.php

Currently, the offhand check in the PlayerItemPickupEvent is not strictly enforced, so there is a possibility that items will disappear.
before:
https://user-images.githubusercontent.com/76860328/131239826-cbc21e26-c15c-420f-870c-239903eda1aa.mp4
after:
https://user-images.githubusercontent.com/76860328/131239828-ab1f2515-32c2-4d29-ada6-7dc609ffee98.mp4

Fix offhand pickup

---

src/entity/Living.php

An entity would turn its head to look at a position, therefore we should calculate the new direction based on eye position, not from feet position.
This change is only logical to prevent copy pasting the same boilerplate code on mob AI plugins just to change one line because it doesn't consider eye position. In addition to this, every entity has an eye position already even if none is provided, PM calculates a default one https://github.com/pmmp/PocketMine-MP/blob/7c943880b24d939514f48b91a3fac91fd103e628/src/entity/EntitySizeInfo.php#L39)
`Location->lookAt()` now takes the entity's eye position into account.

Include eye height in Living->lookAt() calculation

---

changelogs/4.0.md

Added the consts that were removed, which wasn't in the previous README for PM4:
PluginLoadOrder::STARTUP - PluginEnableOrder::STARTUP()
PluginLoadOrder::POSTWORLD - PluginEnableOrder::POSTWORLD()
NONE
NONE
No
NONE
NONE

Added the consts that were removed, which wasn't in the previous README for PM4

---

src/block/BlockFactory.php

Fixed incorrect parameter checking in BlockFactory::get()
https://github.com/pmmp/PocketMine-MP/commit/61c59be299e369878aae00976a970904d7ed8d6b#diff-5ee6ec119d7ba65f7894e25fff09a74933c09607be0e9307011ccbd4cbeffd28R946

Fixed incorrect parameter checking in BlockFactory::get()

---

src/pocketmine/entity/projectile/Projectile.php

Projectiles moving based on motion instead of passed in deltas is unexpected behavior.
This PR applies the fix mentioned in a previous discord conversation.
https://discord.com/channels/373199722573201408/373214753147060235/891732629731295252
- N/A
- N/A
Parameters for the `move` function will now be accounted for.
- No issues
- N/A
Pending Test Results

Account for given deltas in projective move

---

src/world/ChunkLockId.php
src/world/World.php
src/world/generator/PopulationTask.php

PopulationTask must lock chunks to ensure that other PopulationTasks don't try to modify the same chunks at the same time, but this doesn't have to get in the way of general modifications.
Overall, the advent of PM4 has shown it's quite problematic to have chunks randomly become read-only just because some other chunk wanted to be generated.
Instead of a mandatory lock on the used chunks, this PR implements weak locking for chunk population instead. This has all the original benefits of the chunk locking system (as per PM3), with the added advantage that user changes to chunks currently in use by population tasks won't be overwritten.
If a change is made to a locked chunk, the chunk lock is removed. This serves two purposes:
- A new PopulationTask acting on the target chunk can be …

Advisory chunk locking for chunk population

---

src/block/Crops.php
src/block/Sapling.php
src/block/Sugarcane.php
src/block/SweetBerryBush.php

As explained in the issue, right now it's not consistent whether fertilizers are removed if a plant's respective growth event was cancelled.
This PR restores this consistency so that fertilizers are no longer removed from a players inventory if the BlockGrowthEvent / StructureGrowthEvent was cancelled.
* Fixes https://github.com/pmmp/PocketMine-MP/issues/4545
- `Sapling::grow()`'s return type was changed from `void` to `bool`
- `Sugarcane::grow()`'s return type was changed from `void` to `bool`
Fertilizers are no longer removed from the players inventory:
```php
use pocketmine\event\block\BlockGrowEvent;
use pocketmine\event\block\StructureGrowEvent;
use pocketmine\event\Listener;
use pocketmine\plugin\PluginBase;
class TestPlugin extends PluginBase implements Listener {
public function …
```

plants no longer remove fertilizers if respective growth event was cancelled

---

src/world/Position.php

All references from Level got renamed to World in the master branch.
Since this one in the Position class didn't get changed I decided to fix this.

Changed "Level" string to "World" in Position::__toString() method.

---

src/block/Podzol.php

Previously, mining podzol will drop the podzol itself. This Pull Request aims to fix that and change the podzol drop to dirt.
N/A
N/A
N/A
N/A
N/A
N/A

Add correct drop for Podzol

---

src/command/defaults/SetWorldSpawnCommand.php

~~`setworldspawn` command is now consistent with vanilla behavior.~~
Now, the world's spawn position is set to the floored value instead of the rounded value.
World spawn position is no longer using rounded values.

Fix position of setworldspawn command

---

src/command/defaults/SetWorldSpawnCommand.php

This is actually a continuation of #4574.
The input value is now converted to a floor value, and implemented the input of relative coordinates.
- Relative coordinates can now be used.
- Target world is now always the world of the player who executed the command.
- If the command is executed from the console, the default world will be targeted.
- If relative coordinates are entered, the coordinates (0,0,0) will be set as the base point. (This behavior is based on BDS.)

Allow input of relative coordinates to setworldspawn command

---

src/entity/projectile/Projectile.php

https://github.com/pmmp/PocketMine-MP/blob/master/changelogs/4.0.md#general-2
> `Entity->move()` is now `protected`.
but `Projectile->move` is still `public`

Changed visibility of Projectile->move to Protected.

---

src/block/Skull.php

As it is explained in a comment inside the `Skull::recalculateCollisionBoxes()` method, the returned collision box is only correct if the block's facing equals `Facing::UP`.
https://github.com/pmmp/PocketMine-MP/blob/7fd712c1ff5e33c2df8e888f8b3986947f3f4eb4/src/block/Skull.php#L127
This PR aims to change this by implementing the correct calculation of the skulls collision box based on the direction it is facing.

Skull: improve calculation of collision boxes

---

src/Server.php

This is purely an aesthetic change and to prevent confusion to end users, But even though `NetworkInterfaceRegisterEvent` got cancelled, PM4 still logs `pocketmine.server.networkStart` and `pocketmine.server.query.running` to console
- `pocketmine.server.networkStart` is no longer logged to console if their respective `NetworkInterfaceRegisterEvent` gets cancelled

Don't log if NetworkInterfaceRegisterEvent is cancelled

---

src/block/Bed.php

When you try sleeping during the day the message says "Bed is too far away" instead of "You can only sleep at night".

Fixed mistake of "You can only sleep at night" message

---

changelogs/4.0.md

`UUID::toBinary()` no longer exists and was superseded by `Ramsey\Uuid\UuidInterface::getBytes()`
This PR is just to clear up confusion as the 4.0 changelog still shows the aforementioned method.
Changed `Human->getUniqueId()->toBinary()` to `Human->getUniqueId()->getBytes()` in 4.0 changelog

Update changed method in 4.0 changelog
